# Generated by Django 5.2.5 on 2025-08-07 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appoinments', '0004_auto_20250807_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('can_handle_emergencies', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('available_days', models.CharField(blank=True, max_length=100)),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('clinic_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterinarians', to='appoinments.clinicbranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
