# Generated by Django 5.2.5 on 2025-08-07 17:14

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('appoinments', '0001_initial'),
    ]

    operations = []
